openapi: 3.0.0
info:
  title: Export API
  description: API to fetch pledge data and bulk data with optional sorting and pagination.
  version: 1.0.0
servers:
  - url:  https://vak1v0ajec.execute-api.ap-southeast-2.amazonaws.com
    description: Production server
    variables:
      host:
        default:  https://vak1v0ajec.execute-api.ap-southeast-2.amazonaws.com
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
paths:
  /api/pledge/{pledgeId}:
    get:
      summary: Fetch a single pledge
      description: Retrieve a single pledge by its ID from a user-specific table.
      security:
        - basicAuth: []
      parameters:
        - name: pledgeId
          in: path
          description: The ID of the pledge to retrieve.
          required: true
          schema:
            type: string
        - name: Accept
          in: header
          description: Specifies the response format (`application/json` or `application/xml`).
          required: false
          schema:
            type: string
            default: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  amount:
                    type: number
                  status:
                    type: string
            application/xml:
              schema:
                type: string
        '400':
          description: Missing pledgeId in path parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Pledge not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  details:
                    type: string
  /api/pledges:
    get:
      summary: Fetch paginated data
      description: Fetch a paginated list of records with optional sorting and response format.
      security:
        - basicAuth: []
      parameters:
        - name: limit
          in: query
          description: The maximum number of records to retrieve.
          required: false
          schema:
            type: integer
            default: 100
        - name: offset
          in: query
          description: The starting point for records to retrieve (used for pagination).
          required: false
          schema:
            type: integer
            default: 0
        - name: sort_by
          in: query
          description: The column to sort by (e.g., `createdAt`, `updatedAt`).
          required: false
          schema:
            type: string
            enum:
              - createdAt
              - updatedAt
        - name: order_by
          in: query
          description: The sorting order (`asc` for ascending, `desc` for descending).
          required: false
          schema:
            type: string
            enum:
              - asc
              - desc
            default: asc
        - name: Accept
          in: header
          description: Specifies the response format (`application/json` or `application/xml`).
          required: false
          schema:
            type: string
            default: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                  pagination:
                    type: object
                    properties:
                      limit:
                        type: integer
                      offset:
                        type: integer
                      total:
                        type: integer
            application/xml:
              schema:
                type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  details:
                    type: string
